
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientAtServerService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8081/ClientAtServer?wsdl")
public class ClientAtServerService
    extends Service
{

    private final static URL CLIENTATSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTATSERVERSERVICE_EXCEPTION;
    private final static QName CLIENTATSERVERSERVICE_QNAME = new QName("http://server/", "ClientAtServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ClientAtServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTATSERVERSERVICE_WSDL_LOCATION = url;
        CLIENTATSERVERSERVICE_EXCEPTION = e;
    }

    public ClientAtServerService() {
        super(__getWsdlLocation(), CLIENTATSERVERSERVICE_QNAME);
    }

    public ClientAtServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTATSERVERSERVICE_QNAME, features);
    }

    public ClientAtServerService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTATSERVERSERVICE_QNAME);
    }

    public ClientAtServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTATSERVERSERVICE_QNAME, features);
    }

    public ClientAtServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientAtServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientAtServer
     */
    @WebEndpoint(name = "ClientAtServerPort")
    public ClientAtServer getClientAtServerPort() {
        return super.getPort(new QName("http://server/", "ClientAtServerPort"), ClientAtServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientAtServer
     */
    @WebEndpoint(name = "ClientAtServerPort")
    public ClientAtServer getClientAtServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "ClientAtServerPort"), ClientAtServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTATSERVERSERVICE_EXCEPTION!= null) {
            throw CLIENTATSERVERSERVICE_EXCEPTION;
        }
        return CLIENTATSERVERSERVICE_WSDL_LOCATION;
    }

}
